/* Generated by Babel */
'use strict';

var names = ['Will', 'Jack', 'Peter', 'Steve', 'John', 'Hugo', 'Mike', 'sss'];

var newSet = names.map(function (name, index) {
  return {
    id: index,
    name: name
  };
}).filter(function (man) {
  return man.id % 2 == 0;
}).map(function (man) {
  return [man.name];
}).reduce(function (a, b) {
  return a.concat(b);
});

console.log(newSet); //=> [ 'Will', 'Peter', 'John', 'Mike' ]